# Basic pipeline example
trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: python3 --version
    displayName: 'Checking Python Version'

  - script: git --version
    displayName: 'Checking Git Version'

  - script: tree --version
    displayName: 'Checking tree version'

  - script: node -v
    displayName: 'Checking node version' 