trigger:
  - main

pool:
  vmImage: 'ubuntu-24.04'

steps:
  - script: |
      docker --version
      echo "Checked Docker version"
    displayName: 'Check Docker Version'

  - script: |
      docker info
      echo "Checked Docker Engine Status"
    displayName: 'Check Docker Engine Status'

  - script: |
      docker build -t my-python-app .
      echo "Docker image built successfully"
    displayName: 'Build Docker Image'

  - script: |
      docker images
      echo "Listed Docker images"
    displayName: 'List Docker Images'

  - script: |
      docker run --rm my-python-app
      echo "Docker container executed successfully"
    displayName: 'Run Docker Container'

  - script: |
      docker container ls
      echo "Listed running Docker containers"
    displayName: 'List Running Containers'

  - script: |
      docker ps -a
      echo "Listed all Docker containers"
    displayName: 'List All Containers'