trigger:
  - main

pool:
  vmImage: 'ubuntu-24.04'

steps:
  - script: |
      docker --version
      echo "Checked Docker version"
    displayName: 'Checking Docker Version'

  - script: |
      docker info
      echo "Checking Docker Engine Status"
    displayName: 'Checking Docker Engine Status'

  - script: |
      docker build -t my-python-app .
      echo "Docker Image Built Successfully"
    displayName: 'Building Docker Image'

  - script: |
      docker images
      echo "Listing Docker Images"
    displayName: 'Docker Image Listing'

  - script: |
      docker container ls
      echo "Listing Running Docker Containers"
    displayName: 'Docker Container Listing'

  - script: |
      docker ps -a
      echo "Listing All Containers"
    displayName: 'Listing All Containers'